/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as protectedProtectedImport } from './routes/(protected)/_protected'
import { Route as authSignupIndexImport } from './routes/(auth)/signup/index'
import { Route as authSigninIndexImport } from './routes/(auth)/signin/index'
import { Route as protectedProtecteddashboardDashboardImport } from './routes/(protected)/_protected/(dashboard)/_dashboard'
import { Route as protectedProtectedNotesNoteIdIndexImport } from './routes/(protected)/_protected/notes/$noteId/index'
import { Route as protectedProtectedFlashcardsFlashcardIdIndexImport } from './routes/(protected)/_protected/flashcards/$flashcardId/index'
import { Route as protectedProtecteddashboardDashboardNotesIndexImport } from './routes/(protected)/_protected/(dashboard)/_dashboard/notes/index'
import { Route as protectedProtecteddashboardDashboardFlashcardsIndexImport } from './routes/(protected)/_protected/(dashboard)/_dashboard/flashcards/index'

// Create Virtual Routes

const protectedImport = createFileRoute('/(protected)')()
const IndexLazyImport = createFileRoute('/')()
const protectedProtecteddashboardImport = createFileRoute(
  '/(protected)/_protected/(dashboard)',
)()
const protectedProtectedNotesNewIndexLazyImport = createFileRoute(
  '/(protected)/_protected/notes/new/',
)()
const protectedProtectedFlashcardsNewIndexLazyImport = createFileRoute(
  '/(protected)/_protected/flashcards/new/',
)()
const protectedProtecteddashboardDashboardSettingsIndexLazyImport =
  createFileRoute('/(protected)/_protected/(dashboard)/_dashboard/settings/')()
const protectedProtecteddashboardDashboardHomeIndexLazyImport = createFileRoute(
  '/(protected)/_protected/(dashboard)/_dashboard/home/',
)()
const protectedProtecteddashboardDashboardAiIndexLazyImport = createFileRoute(
  '/(protected)/_protected/(dashboard)/_dashboard/ai/',
)()

// Create/Update Routes

const protectedRoute = protectedImport.update({
  id: '/(protected)',
  getParentRoute: () => rootRoute,
} as any)

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const protectedProtectedRoute = protectedProtectedImport.update({
  id: '/_protected',
  getParentRoute: () => protectedRoute,
} as any)

const protectedProtecteddashboardRoute =
  protectedProtecteddashboardImport.update({
    id: '/(dashboard)',
    getParentRoute: () => protectedProtectedRoute,
  } as any)

const authSignupIndexRoute = authSignupIndexImport.update({
  path: '/signup/',
  getParentRoute: () => rootRoute,
} as any)

const authSigninIndexRoute = authSigninIndexImport.update({
  path: '/signin/',
  getParentRoute: () => rootRoute,
} as any)

const protectedProtecteddashboardDashboardRoute =
  protectedProtecteddashboardDashboardImport.update({
    id: '/_dashboard',
    getParentRoute: () => protectedProtecteddashboardRoute,
  } as any)

const protectedProtectedNotesNewIndexLazyRoute =
  protectedProtectedNotesNewIndexLazyImport
    .update({
      path: '/notes/new/',
      getParentRoute: () => protectedProtectedRoute,
    } as any)
    .lazy(() =>
      import('./routes/(protected)/_protected/notes/new/index.lazy').then(
        (d) => d.Route,
      ),
    )

const protectedProtectedFlashcardsNewIndexLazyRoute =
  protectedProtectedFlashcardsNewIndexLazyImport
    .update({
      path: '/flashcards/new/',
      getParentRoute: () => protectedProtectedRoute,
    } as any)
    .lazy(() =>
      import('./routes/(protected)/_protected/flashcards/new/index.lazy').then(
        (d) => d.Route,
      ),
    )

const protectedProtectedNotesNoteIdIndexRoute =
  protectedProtectedNotesNoteIdIndexImport.update({
    path: '/notes/$noteId/',
    getParentRoute: () => protectedProtectedRoute,
  } as any)

const protectedProtectedFlashcardsFlashcardIdIndexRoute =
  protectedProtectedFlashcardsFlashcardIdIndexImport.update({
    path: '/flashcards/$flashcardId/',
    getParentRoute: () => protectedProtectedRoute,
  } as any)

const protectedProtecteddashboardDashboardSettingsIndexLazyRoute =
  protectedProtecteddashboardDashboardSettingsIndexLazyImport
    .update({
      path: '/settings/',
      getParentRoute: () => protectedProtecteddashboardDashboardRoute,
    } as any)
    .lazy(() =>
      import(
        './routes/(protected)/_protected/(dashboard)/_dashboard/settings/index.lazy'
      ).then((d) => d.Route),
    )

const protectedProtecteddashboardDashboardHomeIndexLazyRoute =
  protectedProtecteddashboardDashboardHomeIndexLazyImport
    .update({
      path: '/home/',
      getParentRoute: () => protectedProtecteddashboardDashboardRoute,
    } as any)
    .lazy(() =>
      import(
        './routes/(protected)/_protected/(dashboard)/_dashboard/home/index.lazy'
      ).then((d) => d.Route),
    )

const protectedProtecteddashboardDashboardAiIndexLazyRoute =
  protectedProtecteddashboardDashboardAiIndexLazyImport
    .update({
      path: '/ai/',
      getParentRoute: () => protectedProtecteddashboardDashboardRoute,
    } as any)
    .lazy(() =>
      import(
        './routes/(protected)/_protected/(dashboard)/_dashboard/ai/index.lazy'
      ).then((d) => d.Route),
    )

const protectedProtecteddashboardDashboardNotesIndexRoute =
  protectedProtecteddashboardDashboardNotesIndexImport.update({
    path: '/notes/',
    getParentRoute: () => protectedProtecteddashboardDashboardRoute,
  } as any)

const protectedProtecteddashboardDashboardFlashcardsIndexRoute =
  protectedProtecteddashboardDashboardFlashcardsIndexImport.update({
    path: '/flashcards/',
    getParentRoute: () => protectedProtecteddashboardDashboardRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/(protected)': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof protectedImport
      parentRoute: typeof rootRoute
    }
    '/(protected)/_protected': {
      id: '/_protected'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof protectedProtectedImport
      parentRoute: typeof protectedRoute
    }
    '/(auth)/signin/': {
      id: '/signin/'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof authSigninIndexImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/signup/': {
      id: '/signup/'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof authSignupIndexImport
      parentRoute: typeof rootRoute
    }
    '/(protected)/_protected/(dashboard)': {
      id: '/_protected/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof protectedProtecteddashboardImport
      parentRoute: typeof protectedProtectedImport
    }
    '/(protected)/_protected/(dashboard)/_dashboard': {
      id: '/_protected/_dashboard'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof protectedProtecteddashboardDashboardImport
      parentRoute: typeof protectedProtecteddashboardRoute
    }
    '/(protected)/_protected/flashcards/$flashcardId/': {
      id: '/_protected/flashcards/$flashcardId/'
      path: '/flashcards/$flashcardId'
      fullPath: '/flashcards/$flashcardId'
      preLoaderRoute: typeof protectedProtectedFlashcardsFlashcardIdIndexImport
      parentRoute: typeof protectedProtectedImport
    }
    '/(protected)/_protected/notes/$noteId/': {
      id: '/_protected/notes/$noteId/'
      path: '/notes/$noteId'
      fullPath: '/notes/$noteId'
      preLoaderRoute: typeof protectedProtectedNotesNoteIdIndexImport
      parentRoute: typeof protectedProtectedImport
    }
    '/(protected)/_protected/flashcards/new/': {
      id: '/_protected/flashcards/new/'
      path: '/flashcards/new'
      fullPath: '/flashcards/new'
      preLoaderRoute: typeof protectedProtectedFlashcardsNewIndexLazyImport
      parentRoute: typeof protectedProtectedImport
    }
    '/(protected)/_protected/notes/new/': {
      id: '/_protected/notes/new/'
      path: '/notes/new'
      fullPath: '/notes/new'
      preLoaderRoute: typeof protectedProtectedNotesNewIndexLazyImport
      parentRoute: typeof protectedProtectedImport
    }
    '/(protected)/_protected/(dashboard)/_dashboard/flashcards/': {
      id: '/_protected/_dashboard/flashcards/'
      path: '/flashcards'
      fullPath: '/flashcards'
      preLoaderRoute: typeof protectedProtecteddashboardDashboardFlashcardsIndexImport
      parentRoute: typeof protectedProtecteddashboardDashboardImport
    }
    '/(protected)/_protected/(dashboard)/_dashboard/notes/': {
      id: '/_protected/_dashboard/notes/'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof protectedProtecteddashboardDashboardNotesIndexImport
      parentRoute: typeof protectedProtecteddashboardDashboardImport
    }
    '/(protected)/_protected/(dashboard)/_dashboard/ai/': {
      id: '/_protected/_dashboard/ai/'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof protectedProtecteddashboardDashboardAiIndexLazyImport
      parentRoute: typeof protectedProtecteddashboardDashboardImport
    }
    '/(protected)/_protected/(dashboard)/_dashboard/home/': {
      id: '/_protected/_dashboard/home/'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof protectedProtecteddashboardDashboardHomeIndexLazyImport
      parentRoute: typeof protectedProtecteddashboardDashboardImport
    }
    '/(protected)/_protected/(dashboard)/_dashboard/settings/': {
      id: '/_protected/_dashboard/settings/'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof protectedProtecteddashboardDashboardSettingsIndexLazyImport
      parentRoute: typeof protectedProtecteddashboardDashboardImport
    }
  }
}

// Create and export the route tree

interface protectedProtecteddashboardDashboardRouteChildren {
  protectedProtecteddashboardDashboardFlashcardsIndexRoute: typeof protectedProtecteddashboardDashboardFlashcardsIndexRoute
  protectedProtecteddashboardDashboardNotesIndexRoute: typeof protectedProtecteddashboardDashboardNotesIndexRoute
  protectedProtecteddashboardDashboardAiIndexLazyRoute: typeof protectedProtecteddashboardDashboardAiIndexLazyRoute
  protectedProtecteddashboardDashboardHomeIndexLazyRoute: typeof protectedProtecteddashboardDashboardHomeIndexLazyRoute
  protectedProtecteddashboardDashboardSettingsIndexLazyRoute: typeof protectedProtecteddashboardDashboardSettingsIndexLazyRoute
}

const protectedProtecteddashboardDashboardRouteChildren: protectedProtecteddashboardDashboardRouteChildren =
  {
    protectedProtecteddashboardDashboardFlashcardsIndexRoute:
      protectedProtecteddashboardDashboardFlashcardsIndexRoute,
    protectedProtecteddashboardDashboardNotesIndexRoute:
      protectedProtecteddashboardDashboardNotesIndexRoute,
    protectedProtecteddashboardDashboardAiIndexLazyRoute:
      protectedProtecteddashboardDashboardAiIndexLazyRoute,
    protectedProtecteddashboardDashboardHomeIndexLazyRoute:
      protectedProtecteddashboardDashboardHomeIndexLazyRoute,
    protectedProtecteddashboardDashboardSettingsIndexLazyRoute:
      protectedProtecteddashboardDashboardSettingsIndexLazyRoute,
  }

const protectedProtecteddashboardDashboardRouteWithChildren =
  protectedProtecteddashboardDashboardRoute._addFileChildren(
    protectedProtecteddashboardDashboardRouteChildren,
  )

interface protectedProtecteddashboardRouteChildren {
  protectedProtecteddashboardDashboardRoute: typeof protectedProtecteddashboardDashboardRouteWithChildren
}

const protectedProtecteddashboardRouteChildren: protectedProtecteddashboardRouteChildren =
  {
    protectedProtecteddashboardDashboardRoute:
      protectedProtecteddashboardDashboardRouteWithChildren,
  }

const protectedProtecteddashboardRouteWithChildren =
  protectedProtecteddashboardRoute._addFileChildren(
    protectedProtecteddashboardRouteChildren,
  )

interface protectedProtectedRouteChildren {
  protectedProtecteddashboardRoute: typeof protectedProtecteddashboardRouteWithChildren
  protectedProtectedFlashcardsFlashcardIdIndexRoute: typeof protectedProtectedFlashcardsFlashcardIdIndexRoute
  protectedProtectedNotesNoteIdIndexRoute: typeof protectedProtectedNotesNoteIdIndexRoute
  protectedProtectedFlashcardsNewIndexLazyRoute: typeof protectedProtectedFlashcardsNewIndexLazyRoute
  protectedProtectedNotesNewIndexLazyRoute: typeof protectedProtectedNotesNewIndexLazyRoute
}

const protectedProtectedRouteChildren: protectedProtectedRouteChildren = {
  protectedProtecteddashboardRoute:
    protectedProtecteddashboardRouteWithChildren,
  protectedProtectedFlashcardsFlashcardIdIndexRoute:
    protectedProtectedFlashcardsFlashcardIdIndexRoute,
  protectedProtectedNotesNoteIdIndexRoute:
    protectedProtectedNotesNoteIdIndexRoute,
  protectedProtectedFlashcardsNewIndexLazyRoute:
    protectedProtectedFlashcardsNewIndexLazyRoute,
  protectedProtectedNotesNewIndexLazyRoute:
    protectedProtectedNotesNewIndexLazyRoute,
}

const protectedProtectedRouteWithChildren =
  protectedProtectedRoute._addFileChildren(protectedProtectedRouteChildren)

interface protectedRouteChildren {
  protectedProtectedRoute: typeof protectedProtectedRouteWithChildren
}

const protectedRouteChildren: protectedRouteChildren = {
  protectedProtectedRoute: protectedProtectedRouteWithChildren,
}

const protectedRouteWithChildren = protectedRoute._addFileChildren(
  protectedRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof protectedProtecteddashboardDashboardRouteWithChildren
  '/signin': typeof authSigninIndexRoute
  '/signup': typeof authSignupIndexRoute
  '/flashcards/$flashcardId': typeof protectedProtectedFlashcardsFlashcardIdIndexRoute
  '/notes/$noteId': typeof protectedProtectedNotesNoteIdIndexRoute
  '/flashcards/new': typeof protectedProtectedFlashcardsNewIndexLazyRoute
  '/notes/new': typeof protectedProtectedNotesNewIndexLazyRoute
  '/flashcards': typeof protectedProtecteddashboardDashboardFlashcardsIndexRoute
  '/notes': typeof protectedProtecteddashboardDashboardNotesIndexRoute
  '/ai': typeof protectedProtecteddashboardDashboardAiIndexLazyRoute
  '/home': typeof protectedProtecteddashboardDashboardHomeIndexLazyRoute
  '/settings': typeof protectedProtecteddashboardDashboardSettingsIndexLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof protectedProtecteddashboardDashboardRouteWithChildren
  '/signin': typeof authSigninIndexRoute
  '/signup': typeof authSignupIndexRoute
  '/flashcards/$flashcardId': typeof protectedProtectedFlashcardsFlashcardIdIndexRoute
  '/notes/$noteId': typeof protectedProtectedNotesNoteIdIndexRoute
  '/flashcards/new': typeof protectedProtectedFlashcardsNewIndexLazyRoute
  '/notes/new': typeof protectedProtectedNotesNewIndexLazyRoute
  '/flashcards': typeof protectedProtecteddashboardDashboardFlashcardsIndexRoute
  '/notes': typeof protectedProtecteddashboardDashboardNotesIndexRoute
  '/ai': typeof protectedProtecteddashboardDashboardAiIndexLazyRoute
  '/home': typeof protectedProtecteddashboardDashboardHomeIndexLazyRoute
  '/settings': typeof protectedProtecteddashboardDashboardSettingsIndexLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof protectedRouteWithChildren
  '/_protected': typeof protectedProtectedRouteWithChildren
  '/signin/': typeof authSigninIndexRoute
  '/signup/': typeof authSignupIndexRoute
  '/_protected/': typeof protectedProtecteddashboardRouteWithChildren
  '/_protected/_dashboard': typeof protectedProtecteddashboardDashboardRouteWithChildren
  '/_protected/flashcards/$flashcardId/': typeof protectedProtectedFlashcardsFlashcardIdIndexRoute
  '/_protected/notes/$noteId/': typeof protectedProtectedNotesNoteIdIndexRoute
  '/_protected/flashcards/new/': typeof protectedProtectedFlashcardsNewIndexLazyRoute
  '/_protected/notes/new/': typeof protectedProtectedNotesNewIndexLazyRoute
  '/_protected/_dashboard/flashcards/': typeof protectedProtecteddashboardDashboardFlashcardsIndexRoute
  '/_protected/_dashboard/notes/': typeof protectedProtecteddashboardDashboardNotesIndexRoute
  '/_protected/_dashboard/ai/': typeof protectedProtecteddashboardDashboardAiIndexLazyRoute
  '/_protected/_dashboard/home/': typeof protectedProtecteddashboardDashboardHomeIndexLazyRoute
  '/_protected/_dashboard/settings/': typeof protectedProtecteddashboardDashboardSettingsIndexLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/signin'
    | '/signup'
    | '/flashcards/$flashcardId'
    | '/notes/$noteId'
    | '/flashcards/new'
    | '/notes/new'
    | '/flashcards'
    | '/notes'
    | '/ai'
    | '/home'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/signin'
    | '/signup'
    | '/flashcards/$flashcardId'
    | '/notes/$noteId'
    | '/flashcards/new'
    | '/notes/new'
    | '/flashcards'
    | '/notes'
    | '/ai'
    | '/home'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/_protected'
    | '/signin/'
    | '/signup/'
    | '/_protected/'
    | '/_protected/_dashboard'
    | '/_protected/flashcards/$flashcardId/'
    | '/_protected/notes/$noteId/'
    | '/_protected/flashcards/new/'
    | '/_protected/notes/new/'
    | '/_protected/_dashboard/flashcards/'
    | '/_protected/_dashboard/notes/'
    | '/_protected/_dashboard/ai/'
    | '/_protected/_dashboard/home/'
    | '/_protected/_dashboard/settings/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  protectedRoute: typeof protectedRouteWithChildren
  authSigninIndexRoute: typeof authSigninIndexRoute
  authSignupIndexRoute: typeof authSignupIndexRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  protectedRoute: protectedRouteWithChildren,
  authSigninIndexRoute: authSigninIndexRoute,
  authSignupIndexRoute: authSignupIndexRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/",
        "/signin/",
        "/signup/"
      ]
    },
    "/": {
      "filePath": "(protected)",
      "children": [
        "/_protected"
      ]
    },
    "/_protected": {
      "filePath": "(protected)/_protected.tsx",
      "parent": "/",
      "children": [
        "/_protected/",
        "/_protected/flashcards/$flashcardId/",
        "/_protected/notes/$noteId/",
        "/_protected/flashcards/new/",
        "/_protected/notes/new/"
      ]
    },
    "/signin/": {
      "filePath": "(auth)/signin/index.tsx"
    },
    "/signup/": {
      "filePath": "(auth)/signup/index.tsx"
    },
    "/_protected/": {
      "filePath": "(protected)/_protected/(dashboard)",
      "parent": "/_protected",
      "children": [
        "/_protected/_dashboard"
      ]
    },
    "/_protected/_dashboard": {
      "filePath": "(protected)/_protected/(dashboard)/_dashboard.tsx",
      "parent": "/_protected/",
      "children": [
        "/_protected/_dashboard/flashcards/",
        "/_protected/_dashboard/notes/",
        "/_protected/_dashboard/ai/",
        "/_protected/_dashboard/home/",
        "/_protected/_dashboard/settings/"
      ]
    },
    "/_protected/flashcards/$flashcardId/": {
      "filePath": "(protected)/_protected/flashcards/$flashcardId/index.tsx",
      "parent": "/_protected"
    },
    "/_protected/notes/$noteId/": {
      "filePath": "(protected)/_protected/notes/$noteId/index.tsx",
      "parent": "/_protected"
    },
    "/_protected/flashcards/new/": {
      "filePath": "(protected)/_protected/flashcards/new/index.lazy.tsx",
      "parent": "/_protected"
    },
    "/_protected/notes/new/": {
      "filePath": "(protected)/_protected/notes/new/index.lazy.tsx",
      "parent": "/_protected"
    },
    "/_protected/_dashboard/flashcards/": {
      "filePath": "(protected)/_protected/(dashboard)/_dashboard/flashcards/index.tsx",
      "parent": "/_protected/_dashboard"
    },
    "/_protected/_dashboard/notes/": {
      "filePath": "(protected)/_protected/(dashboard)/_dashboard/notes/index.tsx",
      "parent": "/_protected/_dashboard"
    },
    "/_protected/_dashboard/ai/": {
      "filePath": "(protected)/_protected/(dashboard)/_dashboard/ai/index.lazy.tsx",
      "parent": "/_protected/_dashboard"
    },
    "/_protected/_dashboard/home/": {
      "filePath": "(protected)/_protected/(dashboard)/_dashboard/home/index.lazy.tsx",
      "parent": "/_protected/_dashboard"
    },
    "/_protected/_dashboard/settings/": {
      "filePath": "(protected)/_protected/(dashboard)/_dashboard/settings/index.lazy.tsx",
      "parent": "/_protected/_dashboard"
    }
  }
}
ROUTE_MANIFEST_END */
