/* prettier-ignore-start */

/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file is auto-generated by TanStack Router

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as dashboardDashboardImport } from './routes/(dashboard)/_dashboard'
import { Route as NotesNoteIdIndexImport } from './routes/notes/$noteId/index'
import { Route as FlashcardsFlashcardIdIndexImport } from './routes/flashcards/$flashcardId/index'
import { Route as dashboardDashboardNotesIndexImport } from './routes/(dashboard)/_dashboard/notes/index'
import { Route as dashboardDashboardFlashcardsIndexImport } from './routes/(dashboard)/_dashboard/flashcards/index'

// Create Virtual Routes

const dashboardImport = createFileRoute('/(dashboard)')()
const IndexLazyImport = createFileRoute('/')()
const NotesNewIndexLazyImport = createFileRoute('/notes/new/')()
const FlashcardsNewIndexLazyImport = createFileRoute('/flashcards/new/')()
const authSignupIndexLazyImport = createFileRoute('/(auth)/signup/')()
const authSigninIndexLazyImport = createFileRoute('/(auth)/signin/')()
const dashboardDashboardSettingsIndexLazyImport = createFileRoute(
  '/(dashboard)/_dashboard/settings/',
)()
const dashboardDashboardDashboardIndexLazyImport = createFileRoute(
  '/(dashboard)/_dashboard/dashboard/',
)()
const dashboardDashboardAiIndexLazyImport = createFileRoute(
  '/(dashboard)/_dashboard/ai/',
)()

// Create/Update Routes

const dashboardRoute = dashboardImport.update({
  id: '/(dashboard)',
  getParentRoute: () => rootRoute,
} as any)

const IndexLazyRoute = IndexLazyImport.update({
  path: '/',
  getParentRoute: () => rootRoute,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))

const dashboardDashboardRoute = dashboardDashboardImport.update({
  id: '/_dashboard',
  getParentRoute: () => dashboardRoute,
} as any)

const NotesNewIndexLazyRoute = NotesNewIndexLazyImport.update({
  path: '/notes/new/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/notes/new/index.lazy').then((d) => d.Route),
)

const FlashcardsNewIndexLazyRoute = FlashcardsNewIndexLazyImport.update({
  path: '/flashcards/new/',
  getParentRoute: () => rootRoute,
} as any).lazy(() =>
  import('./routes/flashcards/new/index.lazy').then((d) => d.Route),
)

const authSignupIndexLazyRoute = authSignupIndexLazyImport
  .update({
    path: '/signup/',
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() => import('./routes/(auth)/signup/index.lazy').then((d) => d.Route))

const authSigninIndexLazyRoute = authSigninIndexLazyImport
  .update({
    path: '/signin/',
    getParentRoute: () => rootRoute,
  } as any)
  .lazy(() => import('./routes/(auth)/signin/index.lazy').then((d) => d.Route))

const NotesNoteIdIndexRoute = NotesNoteIdIndexImport.update({
  path: '/notes/$noteId/',
  getParentRoute: () => rootRoute,
} as any)

const FlashcardsFlashcardIdIndexRoute = FlashcardsFlashcardIdIndexImport.update(
  {
    path: '/flashcards/$flashcardId/',
    getParentRoute: () => rootRoute,
  } as any,
)

const dashboardDashboardSettingsIndexLazyRoute =
  dashboardDashboardSettingsIndexLazyImport
    .update({
      path: '/settings/',
      getParentRoute: () => dashboardDashboardRoute,
    } as any)
    .lazy(() =>
      import('./routes/(dashboard)/_dashboard/settings/index.lazy').then(
        (d) => d.Route,
      ),
    )

const dashboardDashboardDashboardIndexLazyRoute =
  dashboardDashboardDashboardIndexLazyImport
    .update({
      path: '/dashboard/',
      getParentRoute: () => dashboardDashboardRoute,
    } as any)
    .lazy(() =>
      import('./routes/(dashboard)/_dashboard/dashboard/index.lazy').then(
        (d) => d.Route,
      ),
    )

const dashboardDashboardAiIndexLazyRoute = dashboardDashboardAiIndexLazyImport
  .update({
    path: '/ai/',
    getParentRoute: () => dashboardDashboardRoute,
  } as any)
  .lazy(() =>
    import('./routes/(dashboard)/_dashboard/ai/index.lazy').then(
      (d) => d.Route,
    ),
  )

const dashboardDashboardNotesIndexRoute =
  dashboardDashboardNotesIndexImport.update({
    path: '/notes/',
    getParentRoute: () => dashboardDashboardRoute,
  } as any)

const dashboardDashboardFlashcardsIndexRoute =
  dashboardDashboardFlashcardsIndexImport.update({
    path: '/flashcards/',
    getParentRoute: () => dashboardDashboardRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/(dashboard)': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof dashboardImport
      parentRoute: typeof rootRoute
    }
    '/(dashboard)/_dashboard': {
      id: '/_dashboard'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof dashboardDashboardImport
      parentRoute: typeof dashboardRoute
    }
    '/flashcards/$flashcardId/': {
      id: '/flashcards/$flashcardId/'
      path: '/flashcards/$flashcardId'
      fullPath: '/flashcards/$flashcardId'
      preLoaderRoute: typeof FlashcardsFlashcardIdIndexImport
      parentRoute: typeof rootRoute
    }
    '/notes/$noteId/': {
      id: '/notes/$noteId/'
      path: '/notes/$noteId'
      fullPath: '/notes/$noteId'
      preLoaderRoute: typeof NotesNoteIdIndexImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/signin/': {
      id: '/signin/'
      path: '/signin'
      fullPath: '/signin'
      preLoaderRoute: typeof authSigninIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/signup/': {
      id: '/signup/'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof authSignupIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/flashcards/new/': {
      id: '/flashcards/new/'
      path: '/flashcards/new'
      fullPath: '/flashcards/new'
      preLoaderRoute: typeof FlashcardsNewIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/notes/new/': {
      id: '/notes/new/'
      path: '/notes/new'
      fullPath: '/notes/new'
      preLoaderRoute: typeof NotesNewIndexLazyImport
      parentRoute: typeof rootRoute
    }
    '/(dashboard)/_dashboard/flashcards/': {
      id: '/_dashboard/flashcards/'
      path: '/flashcards'
      fullPath: '/flashcards'
      preLoaderRoute: typeof dashboardDashboardFlashcardsIndexImport
      parentRoute: typeof dashboardDashboardImport
    }
    '/(dashboard)/_dashboard/notes/': {
      id: '/_dashboard/notes/'
      path: '/notes'
      fullPath: '/notes'
      preLoaderRoute: typeof dashboardDashboardNotesIndexImport
      parentRoute: typeof dashboardDashboardImport
    }
    '/(dashboard)/_dashboard/ai/': {
      id: '/_dashboard/ai/'
      path: '/ai'
      fullPath: '/ai'
      preLoaderRoute: typeof dashboardDashboardAiIndexLazyImport
      parentRoute: typeof dashboardDashboardImport
    }
    '/(dashboard)/_dashboard/dashboard/': {
      id: '/_dashboard/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof dashboardDashboardDashboardIndexLazyImport
      parentRoute: typeof dashboardDashboardImport
    }
    '/(dashboard)/_dashboard/settings/': {
      id: '/_dashboard/settings/'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof dashboardDashboardSettingsIndexLazyImport
      parentRoute: typeof dashboardDashboardImport
    }
  }
}

// Create and export the route tree

interface dashboardDashboardRouteChildren {
  dashboardDashboardFlashcardsIndexRoute: typeof dashboardDashboardFlashcardsIndexRoute
  dashboardDashboardNotesIndexRoute: typeof dashboardDashboardNotesIndexRoute
  dashboardDashboardAiIndexLazyRoute: typeof dashboardDashboardAiIndexLazyRoute
  dashboardDashboardDashboardIndexLazyRoute: typeof dashboardDashboardDashboardIndexLazyRoute
  dashboardDashboardSettingsIndexLazyRoute: typeof dashboardDashboardSettingsIndexLazyRoute
}

const dashboardDashboardRouteChildren: dashboardDashboardRouteChildren = {
  dashboardDashboardFlashcardsIndexRoute:
    dashboardDashboardFlashcardsIndexRoute,
  dashboardDashboardNotesIndexRoute: dashboardDashboardNotesIndexRoute,
  dashboardDashboardAiIndexLazyRoute: dashboardDashboardAiIndexLazyRoute,
  dashboardDashboardDashboardIndexLazyRoute:
    dashboardDashboardDashboardIndexLazyRoute,
  dashboardDashboardSettingsIndexLazyRoute:
    dashboardDashboardSettingsIndexLazyRoute,
}

const dashboardDashboardRouteWithChildren =
  dashboardDashboardRoute._addFileChildren(dashboardDashboardRouteChildren)

interface dashboardRouteChildren {
  dashboardDashboardRoute: typeof dashboardDashboardRouteWithChildren
}

const dashboardRouteChildren: dashboardRouteChildren = {
  dashboardDashboardRoute: dashboardDashboardRouteWithChildren,
}

const dashboardRouteWithChildren = dashboardRoute._addFileChildren(
  dashboardRouteChildren,
)

export interface FileRoutesByFullPath {
  '/': typeof dashboardDashboardRouteWithChildren
  '/flashcards/$flashcardId': typeof FlashcardsFlashcardIdIndexRoute
  '/notes/$noteId': typeof NotesNoteIdIndexRoute
  '/signin': typeof authSigninIndexLazyRoute
  '/signup': typeof authSignupIndexLazyRoute
  '/flashcards/new': typeof FlashcardsNewIndexLazyRoute
  '/notes/new': typeof NotesNewIndexLazyRoute
  '/flashcards': typeof dashboardDashboardFlashcardsIndexRoute
  '/notes': typeof dashboardDashboardNotesIndexRoute
  '/ai': typeof dashboardDashboardAiIndexLazyRoute
  '/dashboard': typeof dashboardDashboardDashboardIndexLazyRoute
  '/settings': typeof dashboardDashboardSettingsIndexLazyRoute
}

export interface FileRoutesByTo {
  '/': typeof dashboardDashboardRouteWithChildren
  '/flashcards/$flashcardId': typeof FlashcardsFlashcardIdIndexRoute
  '/notes/$noteId': typeof NotesNoteIdIndexRoute
  '/signin': typeof authSigninIndexLazyRoute
  '/signup': typeof authSignupIndexLazyRoute
  '/flashcards/new': typeof FlashcardsNewIndexLazyRoute
  '/notes/new': typeof NotesNewIndexLazyRoute
  '/flashcards': typeof dashboardDashboardFlashcardsIndexRoute
  '/notes': typeof dashboardDashboardNotesIndexRoute
  '/ai': typeof dashboardDashboardAiIndexLazyRoute
  '/dashboard': typeof dashboardDashboardDashboardIndexLazyRoute
  '/settings': typeof dashboardDashboardSettingsIndexLazyRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof dashboardRouteWithChildren
  '/_dashboard': typeof dashboardDashboardRouteWithChildren
  '/flashcards/$flashcardId/': typeof FlashcardsFlashcardIdIndexRoute
  '/notes/$noteId/': typeof NotesNoteIdIndexRoute
  '/signin/': typeof authSigninIndexLazyRoute
  '/signup/': typeof authSignupIndexLazyRoute
  '/flashcards/new/': typeof FlashcardsNewIndexLazyRoute
  '/notes/new/': typeof NotesNewIndexLazyRoute
  '/_dashboard/flashcards/': typeof dashboardDashboardFlashcardsIndexRoute
  '/_dashboard/notes/': typeof dashboardDashboardNotesIndexRoute
  '/_dashboard/ai/': typeof dashboardDashboardAiIndexLazyRoute
  '/_dashboard/dashboard/': typeof dashboardDashboardDashboardIndexLazyRoute
  '/_dashboard/settings/': typeof dashboardDashboardSettingsIndexLazyRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/flashcards/$flashcardId'
    | '/notes/$noteId'
    | '/signin'
    | '/signup'
    | '/flashcards/new'
    | '/notes/new'
    | '/flashcards'
    | '/notes'
    | '/ai'
    | '/dashboard'
    | '/settings'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/flashcards/$flashcardId'
    | '/notes/$noteId'
    | '/signin'
    | '/signup'
    | '/flashcards/new'
    | '/notes/new'
    | '/flashcards'
    | '/notes'
    | '/ai'
    | '/dashboard'
    | '/settings'
  id:
    | '__root__'
    | '/'
    | '/_dashboard'
    | '/flashcards/$flashcardId/'
    | '/notes/$noteId/'
    | '/signin/'
    | '/signup/'
    | '/flashcards/new/'
    | '/notes/new/'
    | '/_dashboard/flashcards/'
    | '/_dashboard/notes/'
    | '/_dashboard/ai/'
    | '/_dashboard/dashboard/'
    | '/_dashboard/settings/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexLazyRoute: typeof IndexLazyRoute
  dashboardRoute: typeof dashboardRouteWithChildren
  FlashcardsFlashcardIdIndexRoute: typeof FlashcardsFlashcardIdIndexRoute
  NotesNoteIdIndexRoute: typeof NotesNoteIdIndexRoute
  authSigninIndexLazyRoute: typeof authSigninIndexLazyRoute
  authSignupIndexLazyRoute: typeof authSignupIndexLazyRoute
  FlashcardsNewIndexLazyRoute: typeof FlashcardsNewIndexLazyRoute
  NotesNewIndexLazyRoute: typeof NotesNewIndexLazyRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexLazyRoute: IndexLazyRoute,
  dashboardRoute: dashboardRouteWithChildren,
  FlashcardsFlashcardIdIndexRoute: FlashcardsFlashcardIdIndexRoute,
  NotesNoteIdIndexRoute: NotesNoteIdIndexRoute,
  authSigninIndexLazyRoute: authSigninIndexLazyRoute,
  authSignupIndexLazyRoute: authSignupIndexLazyRoute,
  FlashcardsNewIndexLazyRoute: FlashcardsNewIndexLazyRoute,
  NotesNewIndexLazyRoute: NotesNewIndexLazyRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* prettier-ignore-end */

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/",
        "/flashcards/$flashcardId/",
        "/notes/$noteId/",
        "/signin/",
        "/signup/",
        "/flashcards/new/",
        "/notes/new/"
      ]
    },
    "/": {
      "filePath": "(dashboard)",
      "children": [
        "/_dashboard"
      ]
    },
    "/_dashboard": {
      "filePath": "(dashboard)/_dashboard.tsx",
      "parent": "/",
      "children": [
        "/_dashboard/flashcards/",
        "/_dashboard/notes/",
        "/_dashboard/ai/",
        "/_dashboard/dashboard/",
        "/_dashboard/settings/"
      ]
    },
    "/flashcards/$flashcardId/": {
      "filePath": "flashcards/$flashcardId/index.tsx"
    },
    "/notes/$noteId/": {
      "filePath": "notes/$noteId/index.tsx"
    },
    "/signin/": {
      "filePath": "(auth)/signin/index.lazy.tsx"
    },
    "/signup/": {
      "filePath": "(auth)/signup/index.lazy.tsx"
    },
    "/flashcards/new/": {
      "filePath": "flashcards/new/index.lazy.tsx"
    },
    "/notes/new/": {
      "filePath": "notes/new/index.lazy.tsx"
    },
    "/_dashboard/flashcards/": {
      "filePath": "(dashboard)/_dashboard/flashcards/index.tsx",
      "parent": "/_dashboard"
    },
    "/_dashboard/notes/": {
      "filePath": "(dashboard)/_dashboard/notes/index.tsx",
      "parent": "/_dashboard"
    },
    "/_dashboard/ai/": {
      "filePath": "(dashboard)/_dashboard/ai/index.lazy.tsx",
      "parent": "/_dashboard"
    },
    "/_dashboard/dashboard/": {
      "filePath": "(dashboard)/_dashboard/dashboard/index.lazy.tsx",
      "parent": "/_dashboard"
    },
    "/_dashboard/settings/": {
      "filePath": "(dashboard)/_dashboard/settings/index.lazy.tsx",
      "parent": "/_dashboard"
    }
  }
}
ROUTE_MANIFEST_END */
